### ISSUE TITLE
_createTokenWithCode - What are you trying to say?

### ISSUE THREAD

**Issue by trepidity** [brentvatne/oauth-examples#1]
```    // Warning! You should actually do this part on your server so you don't leak your secret!
    // I only put it here for fun.
    let result = await _createTokenWithCode(code);
```

In this example, it's unclear what you are suggesting should be done instead. Do I need the code?

**Comment by brentvatne** [comment]
I am confused by this question because it leaves out the previous line which is quite important to the comment

Full context:

```
// Warning! You should actually do this part on your server so you don't leak your secret!
// I only put it here for fun.
let result = await _createTokenWithCode(code);
```

If it is still unclear in light of this context please let me know and I will reopen this issue and try to clarify further somehow.

**Comment by trepidity** [comment]
Thanks for the response.
So at https://github.com/brentvatne/oauth-examples/blob/02d7d991e4057ecd806c0eb94009058874896cac/api/authenticateWithGithubAsync.js#L28

You are saying don't do this, do it on the server. Do you mean retrieve and store the code? To me, if it's in the response, it's already leaked. So I don't see how your statement is true or what you are suggesting should be done instead.

**Comment by brentvatne** [comment]
I mean do everything from `_createTokenWithCode` on the server. The only thing you shouldn't leak on the client is the client secret. The secret is not in the response.
